data:
  data_name: cifar10
  dl_kwargs:
    num_workers: 0
  img_size: [32, 32]


model:
  model_name: simple-ae
  factorized_dim: null
  ae:
    in_dim: 3 
    dim_z: 256
    num_scales: 2
    blk_depth: 4
  vq:
    num_codewords: 1024
    embedding_dim: 256
    cos_dist: True
    proj_dim: 8
    random_proj: True

exp:
  lr: 0.0001
  bsz: 128
  steps: 10000
  pretrain_steps: 2000
  beta: 2.0
  log_interval: 5
  eval_interval: 1000
  checkpoint_steps: [5000, 7500]
