data:
  data_name: imagenet
  dl_kwargs:
    num_workers: 16
  img_size: [128, 128]


model:
  model_name: vqgan-ae
  factorized_dim: 12
  ae:
    double_z: False
    z_channels: 256
    resolution: 128
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1,1,2,2,4]  # num_down = len(ch_mult)-1
    num_res_blocks: 2
    attn_resolutions: [8]
    dropout: 0.0
  vq:
    num_codewords: 1024
    embedding_dim: 12
    z_dim: 12
    cos_dist: True
    proj_dim: null
    random_proj: False
    replace_freq: 20


exp:
  lr: 0.000045
  bsz: 16
  steps: 100000
  pretrain_steps: 10000
  beta: 2.0
  log_interval: 5
  eval_interval: 2000
  checkpoint_steps: [50000, 75000]
