data:
  data_name: cifar10
  dl_kwargs:
    num_workers: 0


model:
  model_name: vqgan-ae
  factorized_dim: 8 
  ae:
    double_z: False
    z_channels: 256
    resolution: 32
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1,2,4]  # num_down = len(ch_mult)-1
    num_res_blocks: 2
    attn_resolutions: [8]
    dropout: 0.0
  vq:
    num_codewords: 512
    embedding_dim: 8
    z_dim: 8
    cos_dist: False
    penalty_weight: 0.0


exp:
  lr: 0.0001
  bsz: 12
  steps: 10000
  pretrain_steps: 0
  beta: 2.0
  log_interval: 5
  eval_interval: 1000
