data:
  num_workers: 0


model:
  model_name: resnet-vqvae
  in_dim: 3 
  dim_z: 64
  num_scales: 2
  blk_depth: 1
  num_codewords: 40
  embedding_dim: 64
  cos_dist: False
  proj_dim: null
  random_proj: False
  learnable_codebook: True


exp:
  lr: 0.0002
  bsz: 64
  steps: 2000
  beta: 2.0
  log_interval: 500
