data: 
  data_name: stfdogs
  data_path: ../data/stanforddogs
  img_resolution: [128, 128]
  num_workers: 16


model:
  tokenizer: 
    ae_name: vqgan #vae
    ae_conf: 
      z_channels: 256
      resolution: 128
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [1,1,2,2,4]
      num_res_blocks: 2
      attn_resolutions: [8]
      dropout: 0.0
    qtz_name: vq
    vq_conf:
      num_codewords: 4096
      embedding_dim: 12
      z_dim: 12
      cos_dist: True
      proj_dim: null
      random_proj: False
      replace_freq: 20
      pretrain_steps: 5000
      init_method: latent_random
  
  discriminator:
    input_nc: 3
    ndf: 64
    n_layers: 3
  
  transformer:
    condition_vocab: 120
    max_pos_len: 1024
    d_model: 768
    num_transformer_layers: 12
    num_attn_heads: 12


exp:
  recon:
    lr: 0.0000045
    bsz: 16
    train_steps: 150000
    cm_weight: 2.0
    p_weight: 1.0
    disc_weight: 0.8
    disc_factor: 1.0
    disc_start: 50000
    log_interval: 5
    eval_interval: 5000
    checkpoint_steps: [50000, 100000]
    metrics: ['PSNR', 'SSIM']

  ar:
    lr: 0.000005
    bsz: 16
    train_steps: 100000
    scheduler: cosine
    warmup_steps: 10000
    wd: 0.00001
    betas: [0.9, 0.98]
    z_shape: [16, 16]
    log_interval: 5
    eval_interval: 5000
    checkpoint_steps: [50000, 80000]