data:
  data_name: imagenet
  dl_kwargs:
    num_workers: 16
  img_size: [128, 128]

latent_size: [8, 8]
transformer: 
  num_classes: 100
  max_pos_len: 1024
  d_model: 768
  num_transformer_layers: 12
  num_attn_heads: 12

exp:
  bsz: 32
  lr: 0.000005
  wd: 0.0001
  train_steps: 100000
  scheduler: cosine
  warmup_steps: 10000
  eval_every: 10000
  checkpoint_steps: [50000, 80000]
